language: java
install: true
install: gradle wrapper --gradle-version 4.2

jdk:
  - oraclejdk8

script:
  - ./gradlew build
  - ./gradlew sonarqube -Dsonar.projectKey=hkneptune_Battleship_Java -Dsonar.organization=hkneptune-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3318fae90bf0f6bc70e7a8fe6cfcb3283d23a182

notifications:
  slack: psdhk:qaB5mYmOSZLvEZyDfxmNPyT7
